# Generated by Django 5.2.5 on 2026-09-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_posts_likes_posts_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name': 'Фото поста', 'verbose_name_plural': 'Фотографії постів'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Теми'},
        ),
    ]
