# Generated by Django 5.2.5 on 2026-08-29 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservote',
            options={'verbose_name': 'голоса користувача', 'verbose_name_plural': 'голоси користувача'},
        ),
        migrations.AlterModelOptions(
            name='voting',
            options={'verbose_name': 'голосування', 'verbose_name_plural': 'голосування'},
        ),
        migrations.AlterModelOptions(
            name='votingoption',
            options={'verbose_name': 'опція голосування', 'verbose_name_plural': 'опції голосування'},
        ),
        migrations.AlterField(
            model_name='uservote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votingoption'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voting'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='votingoption',
            name='text',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='votingoption',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.voting'),
        ),
    ]
