# Generated by Django 5.2.5 on 2026-08-15 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(-1, 'Dislike'), (1, 'Like')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='private', max_length=10),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['visibility', '-likes_count'], name='main_portfo_visibil_1f4d82_idx'),
        ),
        migrations.AddField(
            model_name='projectvote',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.portfolioproject'),
        ),
        migrations.AddField(
            model_name='projectvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='projectvote',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_vote_per_user_per_project'),
        ),
    ]
